[package]
name = "snarkos-node-narwhal"
version = "2.1.4"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A Narwhal-style memory pool for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[dependencies.anyhow]
version = "1.0.70"

[dependencies.async-trait]
version = "0.1"

[dependencies.bincode]
version = "1.0"

[dependencies.bytes]
version = "1"

[dependencies.futures]
version = "0.3.27"
features = [ "thread-pool" ]

[dependencies.indexmap]
version = "2.0"
features = [ "serde", "rayon" ]

[dependencies.parking_lot]
version = "0.12"

[dependencies.rand]
version = "0.8"

[dependencies.serde]
version = "1"

[dependencies.sha2]
version = "0.10"
default-features = false

[dependencies.snarkos-account]
path = "../../account"
version = "=2.1.4"

[dependencies.snarkos-node-messages]
path = "../messages"
version = "=2.1.4"

[dependencies.snarkos-node-tcp]
path = "../tcp"
version = "=2.1.4"

[dependencies.snarkvm]
workspace = true
features = [ "async" ]

[dependencies.time]
version = "0.3"

[dependencies.tokio]
version = "1.28"
features = [ "rt" ]

[dependencies.tokio-stream]
version = "=0.1"

[dependencies.tokio-util]
version = "0.7"
features = [ "codec" ]

[dependencies.tracing]
version = "0.1"

[dev-dependencies.axum]
version = "0.6"

[dev-dependencies.axum-extra]
version = "0.7.4"
default-features = false
features = [ "erased-json" ]

[dev-dependencies.open]
version = "4"

[dev-dependencies.rand_chacha]
version = "0.3"

[dev-dependencies.snarkvm]
workspace = true
features = [ "test-helpers" ]

[dev-dependencies.tower-http]
version = "0.4"
features = [ "fs", "trace" ]

[dev-dependencies.tracing-subscriber]
version = "0.3"
features = [ "env-filter" ]

[dev-dependencies]
test-strategy = { git = "https://github.com/frozenlib/test-strategy/", branch = "master"}
proptest = "1.0.0"