[package]
name = "snarkos-rpc"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "RPC for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm-dpc = { version = "0.0.5" }
snarkvm-errors = { version = "0.0.5" }
snarkvm-models = { version = "0.0.5" }
snarkvm-objects = { version = "0.0.5" }
snarkvm-utilities = { version = "0.0.5" }

snarkos-consensus = { path = "../consensus", version = "1.1.4" }
snarkos-network = { path = "../network", version = "1.1.4"}
snarkos-storage = { path = "../storage", version = "1.1.4"}
snarkos-toolkit = { path = "../toolkit", version = "1.1.4"}

anyhow = { version = "1.0.37" }
base64 = { version = "0.13.0" }
chrono = { version = "0.4", features = ["serde"] }
hex = { version = "0.4.2" }
itertools = { version = "0.9.0" }
jsonrpc-core = { version = "17" }
jsonrpc-core-client = { version = "17" }
jsonrpc-derive = { version = "17" }
jsonrpc-http-server = { version = "17" }
parking_lot = { version = "0.11.1" }
rand = { version = "0.8" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.61" }
thiserror = { version = "1.0" }
tokio = { version = "1" }
tracing = { default-features = false, features = ["log"], version = "0.1" }

[dev-dependencies]
snarkos-testing = { path = "../testing" }

jsonrpc-test = { version = "17" }

[build-dependencies]
rustc_version = "0.2"
