[package]
name = "snarkos-rpc"
version = "1.0.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "RPC for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-consensus = { path = "../consensus", version = "1.0.0" }
snarkos-dpc = { path = "../dpc", version = "1.0.0" }
snarkos-errors = { path = "../errors", version = "1.0.0" }
snarkos-models = { path = "../models", version = "1.0.0" }
snarkos-network = { path = "../network", version = "1.0.0" }
snarkos-objects = { path = "../objects", version = "1.0.0" }
snarkos-storage = { path = "../storage", version = "1.0.0" }
snarkos-utilities = { path = "../utilities", version = "1.0.0" }

base64 = { version = "0.12.3" }
chrono = { version = "0.4", features = ["serde"] }
hex = { version = "0.4.2" }
jsonrpc-core = { version = "14.2.0" }
jsonrpc-core-client = { version = "14.0.5" }
jsonrpc-derive = { version = "14.2.1" }
jsonrpc-http-server = { version = "14.2.0" }
rand = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.57" }
tokio = { version = "0.2.22", features = ["full"] }

[dev-dependencies]
snarkos-testing = { path = "../testing", version = "1.0.0" }

jsonrpc-test = { version = "14.2.0" }

[build-dependencies]
rustc_version = "0.2"
