[package]
name = "snarkos-rpc"
version = "0.8.0"
authors = ["The Aleo Team <hello@aleo.org"]
description = "RPC for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-consensus = { path = "../consensus", version = "0.8.0", default-features = false }
snarkos-dpc = { path = "../dpc", version = "0.8.0", default-features = false }
snarkos-errors = { path = "../errors", version = "0.8.0", default-features = false, features = ["rpc"] }
snarkos-network = { path = "../network", version = "0.8.0", default-features = false }
snarkos-objects = { path = "../objects", version = "0.8.0", default-features = false }
snarkos-storage = { path = "../storage", version = "0.8.0", default-features = false }
snarkos-utilities = { path = "../utilities", version = "0.8.0" }

chrono = { version = "0.4", features = ["serde"] }
hex = { version = "0.4.2" }
jsonrpc-core = { version = "14.0.5" }
jsonrpc-core-client = { version = "14.0.5" }
jsonrpc-derive = { version = "14.0.5" }
jsonrpc-http-server = { version = "14.0.5" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
jsonrpc-test = { version = "14.0.5" }
serde_json = { version = "1.0.52" }
