[package]
name = "snarkos-utilities"
version = "2.0.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Utilities for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
    "aleo",
    "cryptography",
    "blockchain",
    "decentralized",
    "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.tokio]
version = "1"
features = ["sync", "rt"]

[dependencies.tracing]
version = "0.1"
