[package]
name = "snarkos-node-consensus"
version = "2.2.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A node consensus for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]

[dependencies.anyhow]
version = "1.0.75"

[dependencies.colored]
version = "2"

[dependencies.indexmap]
version = "2.0"
features = [ "serde", "rayon" ]

[dependencies.lru]
version = "0.12.0"

[dependencies.parking_lot]
version = "0.12"

[dependencies.rand]
version = "0.8"

[dependencies.snarkos-account]
path = "../../account"
version = "=2.2.2"

[dependencies.snarkos-node-bft]
path = "../bft"
version = "=2.2.2"

[dependencies.snarkos-node-bft-ledger-service]
path = "../bft/ledger-service"
version = "=2.2.2"
default-features = false
features = [ "ledger", "ledger-write" ]

[dependencies.snarkvm]
workspace = true

[dependencies.tokio]
version = "1.28"
features = [ "macros", "rt-multi-thread", "signal" ]

[dependencies.tracing]
version = "0.1"

[dev-dependencies.itertools]
version = "0.11"

[dev-dependencies.once_cell]
version = "1.13"

[dev-dependencies.tracing-test]
version = "0.2"
