[package]
name = "snarkos-node-consensus"
version = "2.1.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A node consensus for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]

[dependencies.anyhow]
version = "1.0.70"

[dependencies.parking_lot]
version = "0.12"

[dependencies.snarkvm]
workspace = true

[dependencies.tracing]
version = "0.1"

[dev-dependencies.indexmap]
version = "1.9"

[dev-dependencies.itertools]
version = "0.10"

[dev-dependencies.once_cell]
version = "1.13"

[dev-dependencies.tracing-test]
version = "0.2"
