[package]
name = "snarkos-posw"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Proof of Succinct Work circuit implementation based on [KB20]"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm-algorithms = { version = "0.0.3" }
snarkvm-curves = { version = "0.0.3" } # needed to instantiate with BLS12-377
snarkvm-errors = { version = "0.0.3" }
snarkvm-gadgets = { version = "0.0.3" }
snarkvm-marlin = { version = "0.0.3" }
snarkvm-models = { version = "0.0.3" }
snarkvm-polycommit = { version = "0.0.3" }
snarkvm-objects = { version = "0.0.3" } # needed to instantiate with BLS12-377
snarkvm-parameters = { version = "0.0.3" }
snarkvm-utilities = { version = "0.0.3" }

snarkos-profiler = { path = "../profiler", version = "1.1.4"}

blake2 = { version = "0.8.1" }
rand = { version = "0.7" }
thiserror = "1.0.22"

[dev-dependencies]
rand_xorshift = { version = "0.2" }

[features]
print-trace = [ "snarkos-profiler/print-trace" ]
test-helpers = []
