[package]
name = "snarkos-testing"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Testing suite for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm-algorithms = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }
snarkvm-curves = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }
snarkvm-dpc = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }
snarkvm-errors = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }
snarkvm-models = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }
snarkvm-objects = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }
snarkvm-parameters = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }
snarkvm-utilities = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "f0ff4cd", version = "0.0.2" }

snarkos-consensus = { path = "../consensus", version = "1.1.4" }
snarkos-network = { path = "../network", version = "1.1.4" }
snarkos-posw = { path = "../posw", version = "1.1.4" }
snarkos-storage = { path = "../storage", version = "1.1.4"}

anyhow = { version = "1.0.33" }
once_cell = { version = "1.5.2" }
parking_lot = { version = "0.11.1" }
rand = { version = "0.7.0" }
rand_xorshift = { version = "0.2.0" }
tokio = { version = "0.3", features = ["full"] }
tracing = { default-features = false, features = ["log"], version = "0.1" }
tracing-futures = { version = "0.2" }
tracing-subscriber = { version = "0.2" }

[dev-dependencies]
tokio-test = { version = "0.2.0" }
