[package]
name = "snarkos-testing"
version = "1.3.11"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Testing suite for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[features]
default = [ "network" ]
network = [
  "snarkos-network",
  "snow",
  "tokio",
  "tracing",
  "tracing-futures",
  "tracing-subscriber"
]

[dependencies.snarkvm-algorithms]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "5b24941"

[dependencies.snarkvm-curves]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "5b24941"

[dependencies.snarkvm-dpc]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "5b24941"

[dependencies.snarkvm-parameters]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "5b24941"

[dependencies.snarkvm-posw]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "5b24941"

[dependencies.snarkvm-utilities]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "5b24941"

[dependencies.snarkos-consensus]
path = "../consensus"
version = "1.3.11"

[dependencies.snarkos-network]
path = "../network"
version = "1.3.11"
optional = true

[dependencies.snarkos-storage]
path = "../storage"
version = "1.3.11"
default-features = false
features = [ "test" ]

[dependencies.anyhow]
version = "1.0.40"

[dependencies.bincode]
version = "1.3.1"

[dependencies.once_cell]
version = "1.8"

[dependencies.rand]
version = "0.8"

[dependencies.rand_chacha]
version = "0.3"

[dependencies.rand_xorshift]
version = "0.3"

[dependencies.snow]
version = "0.8"
default-features = false
features = [
  "libsodium-resolver",
  "chacha20poly1305",
  "blake2",
  "sha2",
  "x25519-dalek",
  "rand"
]
optional = true

[dependencies.tokio]
version = "1"
features = [ "macros", "time" ]
optional = true

[dependencies.futures]
version = "0.3"

[dependencies.tracing]
default-features = false
features = [ "log" ]
version = "0.1"
optional = true

[dependencies.tracing-futures]
version = "0.2"
optional = true

[dependencies.tracing-subscriber]
version = "0.2"
optional = true
