[package]
name = "snarkos-testing"
version = "2.0.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
    "aleo",
    "cryptography",
    "blockchain",
    "decentralized",
    "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkos]
path = ".."
features = ["test"]

[dependencies.snarkos-storage]
path = "../storage"

[dependencies.snarkvm]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "e0462bf"
#path = "../../snarkVM"

[dependencies.anyhow]
version = "1"

[dependencies.async-trait]
version = "0.1"

[dependencies.bincode]
version = "1"

[dependencies.pea2pea]
version = "0.32"

[dependencies.peak_alloc]
version = "0.1"

[dependencies.rand]
version = "0.8"

[dependencies.structopt]
version = "0.3"

[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread", "time"]

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter", "parking_lot"]
