[package]
name = "snarkos-testing"
version = "1.2.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Testing suite for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-algorithms]
version = "0.0.5"

[dependencies.snarkvm-curves]
version = "0.0.5"

[dependencies.snarkvm-dpc]
version = "0.0.5"

[dependencies.snarkvm-errors]
version = "0.0.5"

[dependencies.snarkvm-models]
version = "0.0.5"

[dependencies.snarkvm-objects]
version = "0.0.5"

[dependencies.snarkvm-parameters]
version = "0.0.5"

[dependencies.snarkvm-posw]
version = "0.0.5"

[dependencies.snarkvm-utilities]
version = "0.0.5"

[dependencies.snarkos]
path = "../" 
version = "1.2.0"

[dependencies.snarkos-consensus]
path = "../consensus"
version = "1.2.0"

[dependencies.snarkos-network]
path = "../network"
version = "1.2.0"

[dependencies.snarkos-parameters]
path = "../parameters"
version = "1.2.0"

[dependencies.snarkos-storage]
path = "../storage"
version = "1.2.0"

[dependencies.anyhow]
version = "1.0.33"

[dependencies.bincode]
version = "1.3.1"

[dependencies.once_cell]
version = "1.5.2"

[dependencies.parking_lot]
version = "0.11.1"

[dependencies.rand]
version = "0.8"

[dependencies.rand_xorshift]
version = "0.3"

[dependencies.snow]
version = "0.7"
default-features = false
features = [
  "libsodium-resolver",
  "chacha20poly1305",
  "blake2",
  "sha2",
  "x25519-dalek",
  "rand"
]

[dependencies.tokio]
version = "1"
features = [ "macros", "time" ]

[dependencies.tracing]
default-features = false
features = [ "log" ]
version = "0.1"

[dependencies.tracing-futures]
version = "0.2"

[dependencies.tracing-subscriber]
version = "0.2"
