[package]
name = "snarkos-testing"
version = "1.0.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Testing suite for a decentralized record system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["cryptography", "blockchain", "decentralized", "record", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-algorithms = { path = "../algorithms", version = "1.0.0" }
snarkos-consensus = { path = "../consensus", version = "1.0.0" }
snarkos-curves = { path = "../curves", version = "1.0.0" }
snarkos-dpc = { path = "../dpc", version = "1.0.0" }
snarkos-errors = { path = "../errors", version = "1.0.0" }
snarkos-models = { path = "../models", version = "1.0.0" }
snarkos-network = { path = "../network", version = "1.0.0" }
snarkos-objects = { path = "../objects", version = "1.0.0" }
snarkos-parameters = { path = "../parameters", version = "1.0.0" }
snarkos-posw = { path = "../posw", version = "1.0.0" }
snarkos-storage = { path = "../storage", version = "1.0.0" }
snarkos-utilities = { path = "../utilities", version = "1.0.0" }

once_cell = { version = "1.4.0" }
rand = { version = "0.7.0" }
rand_xorshift = { version = "0.2.0" }
tokio = { version = "0.2.22", features = ["full"] }
