[package]
name = "snarkos-testing"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Testing suite for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm-algorithms = { version = "0.0.3" }
snarkvm-curves = { version = "0.0.3" }
snarkvm-dpc = { version = "0.0.3" }
snarkvm-errors = { version = "0.0.3" }
snarkvm-models = { version = "0.0.3" }
snarkvm-objects = { version = "0.0.3" }
snarkvm-parameters = { version = "0.0.3" }
snarkvm-utilities = { version = "0.0.3" }

snarkos-consensus = { path = "../consensus", version = "1.1.4" }
snarkos-network = { path = "../network", version = "1.1.4" }
snarkos-posw = { path = "../posw", version = "1.1.4" }
snarkos-storage = { path = "../storage", version = "1.1.4"}

anyhow = { version = "1.0.33" }
bincode = { version = "1.3.1" }
once_cell = { version = "1.5.2" }
parking_lot = { version = "0.11.1" }
rand = { version = "0.7.0" }
rand_xorshift = { version = "0.2.0" }
snow = { version = "0.7", default-features = false, features = ["libsodium-resolver", "chacha20poly1305", "blake2", "sha2", "x25519-dalek", "rand"] }
tokio = { version = "1", features = ["macros", "time"] }
tracing = { default-features = false, features = ["log"], version = "0.1" }
tracing-futures = { version = "0.2" }
tracing-subscriber = { version = "0.2" }
