blank_issues_enabled: true
contact_links:
  - name: â“ Q&A Support Channel
    url: https://discord.gg/zvvSjeN
    about: For quick questions or technical troubleshooting, please ask them on our dedicated Discord channel. ğŸ¥
