[package]
name = "snarkos-network"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Network for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-algorithms = { path = "../algorithms", version = "1.1.4"}
snarkos-consensus = { path = "../consensus", version = "1.1.4"}
snarkos-dpc = { path = "../dpc", version = "1.1.4"}
snarkos-errors = { path = "../errors", version = "1.1.4"}
snarkos-metrics = { path = "../metrics", version = "1.1.4"}
snarkos-models = { path = "../models", version = "1.1.4"}
snarkos-objects = { path = "../objects", version = "1.1.4"}
snarkos-storage = { path = "../storage", version = "1.1.4"}
snarkos-utilities = { path = "../utilities", version = "1.1.4"}

bincode = { version = "1.3.1" }
byteorder = { version = "1" }
chrono = { version = "0.4", features = ["serde"] }
hex = { version = "0.4.2" }
log = { version = "0.4.11" }
rand = { version = "0.7.3" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2.22", features = ["full"] }
tracing = { version = "0.1.19" }

[dev-dependencies]
snarkos-testing = { path = "../testing" }

serial_test = { version = "0.5.0" }
tokio-test = { version = "0.2.0" }

[build-dependencies]
rustc_version = "0.2"
