[package]
name = "snarkos-node-sync"
version = "2.2.7"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A synchronization module for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoNet/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]
metrics = [ "dep:metrics" ]
test = [ "snarkos-node-sync-locators/test" ]

[dependencies.anyhow]
version = "1.0"

[dependencies.indexmap]
version = "2.1"
features = [ "serde", "rayon" ]

[dependencies.itertools]
version = "0.12"

[dependencies.once_cell]
version = "1"

[dependencies.parking_lot]
version = "0.12"

[dependencies.rand]
version = "0.8"

[dependencies.serde]
version = "1"

[dependencies.snarkos-node-bft-ledger-service]
path = "../bft/ledger-service"
version = "=2.2.7"
features = [ "ledger-write" ]

[dependencies.metrics]
package = "snarkos-node-metrics"
path = "../metrics"
version = "=2.2.7"
optional = true

[dependencies.snarkos-node-router]
path = "../router"
version = "=2.2.7"

[dependencies.snarkos-node-sync-communication-service]
path = "communication-service"
version = "=2.2.7"

[dependencies.snarkos-node-sync-locators]
path = "locators"
version = "=2.2.7"

[dependencies.snarkvm]
workspace = true

[dependencies.tokio]
version = "1.28"
features = [ "rt", "signal" ]

[dependencies.tracing]
version = "0.1"

[dev-dependencies.snarkos-node-bft-ledger-service]
path = "../bft/ledger-service"
features = [ "test" ]

[dev-dependencies.snarkos-node-sync-locators]
path = "locators"
features = [ "test" ]

[dev-dependencies.snarkvm]
workspace = true
features = [ "test-helpers" ]
