[package]
name = "snarkos-toolkit"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "A developer toolkit for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "account"
path = "benches/account.rs"
harness = false

[dependencies]
snarkvm-algorithms = { git="https://github.com/AleoHQ/snarkVM", rev="d9da9ad62cb8bb5b7a6d2bedb959c578cfc770cc", version = "0.0.4" }
snarkvm-dpc = { git="https://github.com/AleoHQ/snarkVM", rev="d9da9ad62cb8bb5b7a6d2bedb959c578cfc770cc", version = "0.0.4" }
snarkvm-errors = { git="https://github.com/AleoHQ/snarkVM", rev="d9da9ad62cb8bb5b7a6d2bedb959c578cfc770cc", version = "0.0.4" }
snarkvm-models = { git="https://github.com/AleoHQ/snarkVM", rev="d9da9ad62cb8bb5b7a6d2bedb959c578cfc770cc", version = "0.0.4" }
snarkvm-objects = { git="https://github.com/AleoHQ/snarkVM", rev="d9da9ad62cb8bb5b7a6d2bedb959c578cfc770cc", version = "0.0.4" }
snarkvm-utilities = { git="https://github.com/AleoHQ/snarkVM", rev="d9da9ad62cb8bb5b7a6d2bedb959c578cfc770cc", version = "0.0.4" }

anyhow = { version = "1.0.37" }
hex = { version = "0.4.2" }
rand = { version = "0.8" }
thiserror = { version = "1.0" }
wasm-bindgen = { version = "0.2.70" }

[dev-dependencies]
criterion = { version = "0.3.1" }
hex = { version = "0.4.2" }
rand_chacha = { version = "0.3", default-features = false }
wasm-bindgen-test = { version = "0.3.18" }
