[package]
name = "snarkos-toolkit"
version = "1.3.4"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A developer toolkit for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = [ "cdylib", "rlib" ]

[[bench]]
name = "account"
path = "benches/account.rs"
harness = false

[dependencies.snarkvm-algorithms]
version = "0.2.2"
default-features = false
features = [ "wasm" ]

[dependencies.snarkvm-dpc]
version = "0.2.2"
default-features = false

[dependencies.snarkvm-objects]
version = "0.3.1"
default-features = false

[dependencies.snarkvm-utilities]
version = "0.2.2"

[dependencies.anyhow]
version = "1.0.40"

[dependencies.hex]
version = "0.4.2"

[dependencies.rand]
version = "0.8"
default-features = false

[dependencies.getrandom]
version = "0.2.2"
features = [ "js" ]

[dependencies.thiserror]
version = "1.0"

[dependencies.wasm-bindgen]
version = "0.2.73"

[dev-dependencies.criterion]
version = "0.3.1"

[dev-dependencies.hex]
version = "0.4.2"

[dev-dependencies.rand_chacha]
version = "0.3"
default-features = false

[dev-dependencies.wasm-bindgen-test]
version = "0.3.23"
