[package]
name = "snarkos-node-bft"
version = "2.2.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A memory pool for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[dependencies.anyhow]
version = "1.0.70"

[dependencies.async-recursion]
version = "1.0"

[dependencies.async-trait]
version = "0.1"

[dependencies.bytes]
version = "1"

[dependencies.colored]
version = "2"

[dependencies.futures]
version = "0.3.27"
features = [ "thread-pool" ]

[dependencies.indexmap]
version = "2.0"
features = [ "serde", "rayon" ]

[dependencies.parking_lot]
version = "0.12"

[dependencies.rand]
version = "0.8"

[dependencies.rayon]
version = "1"

[dependencies.serde]
version = "1"

[dependencies.sha2]
version = "0.10"
default-features = false

[dependencies.snarkos-account]
path = "../../account"
version = "=2.2.1"

[dependencies.snarkos-node-bft-events]
path = "./events"
version = "=2.2.1"

[dependencies.snarkos-node-bft-ledger-service]
path = "./ledger-service"
version = "=2.2.1"
features = [ "ledger", "prover" ]

[dependencies.snarkos-node-sync]
path = "../sync"
version = "=2.2.1"

[dependencies.snarkos-node-tcp]
path = "../tcp"
version = "=2.2.1"

[dependencies.snarkvm]
workspace = true

[dependencies.snow]
version = "0.9"

[dependencies.time]
version = "0.3"

[dependencies.tokio]
version = "1.28"
features = [ "macros", "rt-multi-thread", "signal" ]

[dependencies.tokio-stream]
version = "=0.1"

[dependencies.tokio-util]
version = "0.7"
features = [ "codec" ]

[dependencies.tracing]
version = "0.1"

[dev-dependencies.axum]
version = "0.6"

[dev-dependencies.axum-extra]
version = "0.8.0"
default-features = false
features = [ "erased-json" ]

[dev-dependencies.clap]
version = "4.3"

[dev-dependencies.deadline]
version = "0.2"

[dev-dependencies.itertools]
version = "0.11"

[dev-dependencies.open]
version = "5"

[dev-dependencies.paste]
version = "1"

[dev-dependencies.proptest]
version = "1.3.1"

[dev-dependencies.rand_chacha]
version = "0.3"

[dev-dependencies.rand_distr]
version = "0.4"

[dev-dependencies.rayon]
version = "1"

[dev-dependencies.snarkos-node-bft-ledger-service]
path = "./ledger-service"
default-features = false
features = [ "test" ]

[dev-dependencies.snarkvm]
workspace = true
features = [ "test-helpers" ]

[dev-dependencies.test-strategy]
version = "0.3.1"

[dev-dependencies.tower-http]
version = "0.4"
features = [ "fs", "trace" ]

[dev-dependencies.tracing-subscriber]
version = "0.3"
features = [ "env-filter" ]

[dev-dependencies.tracing-test]
version = "0.1"

[dev-dependencies.mockall]
version = "0.11.4"
