[package]
name = "snarkos-parameters"
version = "1.0.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Parameters for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-algorithms = { path = "../algorithms", version = "1.0.0", default-features = false }
snarkos-errors = { path = "../errors", version = "1.0.0", default-features = false }
snarkos-models = { path = "../models", version = "1.0.0", default-features = false }
snarkos-utilities = { path = "../utilities", version = "1.0.0", default-features = false }

curl = { version = "0.4.33", optional = true }
hex = { version = "0.4.2" }

[dev-dependencies]
snarkos-algorithms = { path = "../algorithms", version = "1.0.0" }
snarkos-consensus = { path = "../consensus", version = "1.0.0" }
snarkos-curves = { path = "../curves", version = "1.0.0" }
snarkos-dpc = { path = "../dpc", version = "1.0.0" }
snarkos-objects = { path = "../objects", version = "1.0.0" }
snarkos-posw = { path = "../posw", version = "1.0.0", features = ["test-helpers"] }
snarkos-storage = { path = "../storage", version = "1.0.0" }

snarkos-marlin = { path = "../marlin", version = "1.0.0" }

chrono = { version = "0.4", features = ["serde"] }
curl = { version = "0.4.33" }
hex = { version = "0.4.2" }
parking_lot = { version = "0.11.0" }
rand = { version = "0.7" }

[features]
default = [ "remote", "snarkos-algorithms/default", "snarkos-errors/default", "snarkos-models/default" ]
remote = [ "curl", "snarkos-errors/remote" ]
