[package]
name = "snarkos-parameters"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Parameters for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm-algorithms = { version = "0.0.4", default-features = false }
snarkvm-errors = { version = "0.0.4", default-features = false }
snarkvm-models = { version = "0.0.4", default-features = false }
snarkvm-utilities = { version = "0.0.4", default-features = false }

curl = { version = "0.4.34", optional = true }
hex = { version = "0.4.2" }

[dev-dependencies]
snarkvm-curves = { version = "0.0.4" }
snarkvm-dpc = { version = "0.0.4" }
snarkvm-marlin = { version = "0.0.4" }
snarkvm-objects = { version = "0.0.4" }

snarkos-consensus = { path = "../consensus", version = "1.1.4" }
snarkos-posw = { path = "../consensus", version = "1.1.4" }
snarkos-storage = { path = "../consensus", version = "1.1.4" }

chrono = { version = "0.4", features = ["serde"] }
curl = { version = "0.4.34" }
hex = { version = "0.4.2" }
parking_lot = { version = "0.11.1" }
rand = { version = "0.7" }

[features]
default = [ "remote", "snarkvm-algorithms/default", "snarkvm-models/default" ]
remote = [ "curl" ]
