[package]
name = "snarkos-storage"
version = "2.0.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Storage for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2018"

[[bench]]
name = "lookups"
harness = false

[[bench]]
name = "insertion"
harness = false

[[bench]]
name = "opening"
harness = false

[dependencies.snarkvm]
version = "0.8.0"

[dependencies.anyhow]
version = "1"

[dependencies.bincode]
version = "1.0"
optional = true

[dependencies.circular-queue]
version = "0.2"

[dependencies.itertools]
version = "0.10"

[dependencies.parking_lot]
version = "0.12"

[dependencies.rand]
version = "0.8"

[dependencies.rayon]
version = "1"

[dependencies.rocksdb]
version = "0.18"
optional = true
default-features = false
features = [ "snappy" ]

[dependencies.serde]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.time]
version = "0.3.7"

[dependencies.tracing]
version = "0.1"

[dev-dependencies.criterion]
version = "0.3"

[dev-dependencies.rand_xorshift]
version = "0.3"

[dev-dependencies.tempfile]
version = "3.2"

[features]
default = [ "rocks" ]
rocks = [ "bincode", "rocksdb" ]
