[package]
name = "snarkos-storage"
version = "1.3.14"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Storage for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[features]
default = [ "rocksdb_storage" ]
rocksdb_storage = [ "rocksdb" ]
mem_storage = [ ]
test = [ ]

[dependencies.snarkvm-algorithms]
version = "=0.7.9"

[dependencies.snarkvm-dpc]
version = "=0.7.9"

[dependencies.snarkvm-parameters]
version = "=0.7.9"

[dependencies.snarkvm-utilities]
version = "=0.7.9"

[dependencies.snarkos-metrics]
path = "../metrics"

[dependencies.snarkos-parameters]
path = "../parameters"
version = "1.3.14"

[dependencies.derivative]
version = "2.2.0"

[dependencies.blake2]
version = "0.9"

[dependencies.smallvec]
version = "1.6"
features = [ "write" ]

[dependencies.anyhow]
version = "1.0.40"

[dependencies.bincode]
version = "1.3.1"

[dependencies.hex]
version = "0.4.2"

[dependencies.indexmap]
version = "1.6"

[dependencies.num_enum]
version = "0.5"

[dependencies.parking_lot]
version = "0.11"

[dependencies.rand]
version = "0.8"

[dependencies.rocksdb]
version = "0.17.0"
optional = true

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.thiserror]
version = "1.0"

[dependencies.async-trait]
version = "0.1"

[dependencies.tokio]
version = "1"
features = [
  "io-util",
  "parking_lot",
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
  "time"
]

[dependencies.futures]
version = "0.3"

[dependencies.tracing]
default-features = false
features = [ "log" ]
version = "0.1"

[dev-dependencies.snarkos-consensus]
path = "../consensus"

[dev-dependencies.snarkvm-curves]
version = "=0.7.9"

[dev-dependencies.tracing-subscriber]
version = "0.2"
