[package]
name = "snarkos-storage"
version = "2.0.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Storage for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
    "aleo",
    "cryptography",
    "blockchain",
    "decentralized",
    "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "459ea96" }
#snarkvm = { path = "../../snarkVM" }

[dependencies.anyhow]
version = "1"

[dependencies.bincode]
version = "1.0"
optional = true

[dependencies.chrono]
version = "0.4"
default-features = false
features = [ "clock", "serde" ]

[dependencies.circular-queue]
version = "0.2"

[dependencies.itertools]
version = "0.10"

[dependencies.parking_lot]
version = "0.11"

[dependencies.rand]
version = "0.8"

[dependencies.rayon]
version = "1"

[dependencies.rocksdb]
version = "0.17"
optional = true

[dependencies.serde]
version = "1"

[dependencies.serde_json]
version = "1"

[dependencies.tracing]
version = "0.1"

[dev-dependencies.tempfile]
version = "3.3"

[features]
default = ["rocks"]
rocks = ["bincode", "rocksdb"]
