[package]
name = "snarkos-storage"
version = "1.2.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Storage for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-algorithms]
version = "0.0.5"

[dependencies.snarkvm-objects]
version = "0.0.5"

[dependencies.snarkvm-errors]
version = "0.0.6"

[dependencies.snarkvm-models]
version = "0.0.5"

[dependencies.snarkvm-parameters]
version = "0.0.5"

[dependencies.snarkvm-utilities]
version = "0.0.5"

[dependencies.snarkos-parameters]
path = "../parameters"
version = "1.2.0"

[dependencies.anyhow]
version = "1.0.37"

[dependencies.bincode]
version = "1.3.1"

[dependencies.hex]
version = "0.4.2"

[dependencies.parking_lot]
version = "0.11.1"

[dependencies.rand]
version = "0.8"

[dependencies.rocksdb]
version = "0.15.0"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.thiserror]
version = "1.0"

[dev-dependencies.snarkos-consensus]
path = "../consensus"

[dev-dependencies.snarkvm-curves]
version = "0.0.5"

[dev-dependencies.snarkos-testing]
path = "../testing"
