[package]
name = "snarkos-storage"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Storage for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm-algorithms = { version = "0.0.3"}
snarkvm-objects = { version = "0.0.3" }
snarkvm-errors = { version = "0.0.3" }
snarkvm-models = { version = "0.0.3" }
snarkvm-parameters = { version = "0.0.3" }
snarkvm-utilities = { version = "0.0.3" }

anyhow = { version = "1.0.37" }
bincode = { version = "1.3.1" }
hex = { version = "0.4.2" }
parking_lot = { version = "0.11.1" }
rand = { version = "0.7" }
rocksdb = { version = "0.15.0" }
serde = { version = "1.0", features = ["derive"] }
thiserror = { version = "1.0" }

[dev-dependencies]
snarkos-consensus = { path = "../consensus" }

snarkvm-curves = { version = "0.0.3" }

snarkos-testing = { path = "../testing" }
