[package]
name = "snarkos-node-bft-events"
version = "2.2.7"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Events for the gateway in a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoNet/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]
metrics = ["dep:metrics", "snarkvm/metrics"]

[dependencies.anyhow]
version = "1.0"

[dependencies.bytes]
version = "1"

[dependencies.indexmap]
version = "2.1"
features = [ "serde", "rayon" ]

[dependencies.metrics]
package = "snarkos-node-metrics"
path = "../../metrics"
version = "=2.2.7"
optional = true

[dependencies.rayon]
version = "1"

[dependencies.serde]
version = "1"

[dependencies.snarkos-node-sync-locators]
path = "../../sync/locators"
version = "=2.2.7"

[dependencies.snarkvm]
workspace = true

[dependencies.tokio-util]
version = "0.7"
features = [ "codec" ]

[dependencies.tracing]
version = "0.1"

[dev-dependencies.proptest]
version = "1.4.0"

[dev-dependencies.snarkvm]
workspace = true
features = [ "test-helpers" ]

[dev-dependencies.test-strategy]
version = "0.3.1"

[dev-dependencies.time]
version = "0.3"

[dev-dependencies.snarkos-node-sync-locators]
path = "../../sync/locators"
features = [ "test" ]
