[package]
name = "marlin"
version = "0.1.0"
authors = [
  "Alessandro Chiesa <alexch@berkeley.edu>",
  "Mary Maller <mary.maller.15@ucl.ac.uk>",
  "Yuncong Hu <huyuncongh@gmail.com>",
  "Pratyush Mishra <pratyush@berkeley.edu>",
  "Noah Vesely <noah.vesely.18@ucl.ac.uk>",
  "Nicholas Ward <npward@berkeley.edu>",
]
description = "A library for the Marlin preprocessing zkSNARK"
repository = "https://github.com/scipr/marlin"
documentation = "https://docs.rs/marlin/"
keywords = ["cryptography", "polynomial commitments", "zkSNARK"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
snarkos-algorithms = { git = "ssh://git@github.com/AleoHQ/snarkOS.git" }
snarkos-errors = { git = "ssh://git@github.com/AleoHQ/snarkOS.git" }
snarkos-gadgets = { git = "ssh://git@github.com/AleoHQ/snarkOS.git" }
snarkos-models = { git = "ssh://git@github.com/AleoHQ/snarkOS.git" }
snarkos-profiler = { git = "ssh://git@github.com/AleoHQ/snarkOS.git" }
snarkos-utilities = { git = "ssh://git@github.com/AleoHQ/snarkOS.git" }

poly-commit = { git = "ssh://git@github.com/AleoHQ/poly-commit.git", default-features = false }

blake2 = { version = "0.8", default-features = false }
derivative = { version = "2", features = ["use_core"] }
digest = { version = "0.8" }
rand_core = { version = "0.5" }
rand_chacha = { version = "0.2.1", default-features = false }
rayon = { version = "1", optional = true }

[dev-dependencies]
snarkos-curves = { git = "ssh://git@github.com/AleoHQ/snarkOS.git" }

rusty-hook = { version = "0.11.1" }

[profile.release]
opt-level = 3
lto = "thin"
incremental = true
debug = true

[profile.test]
opt-level = 3
debug-assertions = true
incremental = true
debug = true

[features]
default = [ "std", "parallel" ]
std = [ "poly-commit/std" ]
print-trace = [ "snarkos-profiler/print-trace" ]
parallel = [ "std", "rayon" ]
