[package]
name = "snarkos-consensus"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Consensus for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkvm-algorithms = { version = "0.0.3" }
snarkvm-curves = { version = "0.0.3" }
snarkvm-dpc = { version = "0.0.3" }
snarkvm-errors = { version = "0.0.3" }
snarkvm-models = { version = "0.0.3" }
snarkvm-objects = { version = "0.0.3" }
snarkvm-utilities = { version = "0.0.3" }

snarkos-posw = { path = "../posw", version = "1.1.4"}
snarkos-profiler = { path = "../profiler", version = "1.1.4"}
snarkos-storage = { path = "../storage", version = "1.1.4"}

anyhow = { version = "1.0.37" }
chrono = { version = "0.4", features = ["serde"] }
hex = { version = "0.4.2" }
parking_lot = { version = "0.11.1" }
rand = { version = "0.7.3" }
thiserror = { version = "1.0" }
tracing = { default-features = false, features = ["log"], version = "0.1" }

[dev-dependencies]
snarkos-testing = { path = "../testing" }

criterion = { version = "0.3" }
rand_xorshift = { version = "0.3" }

[[bench]]
name = "transactions"
path = "benches/transactions.rs"
harness = false
