[package]
name = "snarkos-consensus"
version = "1.3.13"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Consensus for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.snarkvm-algorithms]
version = "=0.7.8"

[dependencies.snarkvm-curves]
version = "=0.7.8"

[dependencies.snarkvm-dpc]
version = "=0.7.8"

[dependencies.snarkvm-posw]
version = "=0.7.8"

[dependencies.snarkvm-utilities]
version = "=0.7.8"

[dependencies.metrics]
version = "0.17"

[dependencies.snarkvm-parameters]
version = "=0.7.8"

[dependencies.tokio]
version = "1"

[dependencies.snarkos-metrics]
path = "../metrics"
version = "1.3.13"

[dependencies.snarkos-profiler]
path = "../profiler"
version = "1.3.13"

[dependencies.snarkos-storage]
path = "../storage"
version = "1.3.13"
default-features = false

[dependencies.anyhow]
version = "1.0.40"

[dependencies.chrono]
version = "0.4"
features = [ "serde" ]

[dependencies.hex]
version = "0.4.2"

[dependencies.smallvec]
version = "1.6"

[dependencies.rand]
version = "0.8"

[dependencies.thiserror]
version = "1.0"

[dependencies.mpmc-map]
version = "0.2"

[dependencies.indexmap]
version = "1.6"

[dependencies.lazy_static]
version = "1.4"

[dependencies.dyn-clone]
version = "1.0"

[dependencies.tracing]
default-features = false
features = [ "log" ]
version = "0.1"

[dev-dependencies.snarkos-testing]
path = "../testing"

[dev-dependencies.criterion]
version = "0.3"

[dev-dependencies.rand_chacha]
version = "0.3"

[dev-dependencies.rand_xorshift]
version = "0.3"

[dev-dependencies.tracing-subscriber]
version = "0.2"

[[bench]]
name = "transactions"
path = "benches/transactions.rs"
harness = false
