[package]
name = "snarkos-consensus"
version = "1.0.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Consensus for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["operating systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
snarkos-algorithms = { path = "../algorithms", version = "1.0.0" }
snarkos-curves = { path = "../curves", version = "1.0.0" }
snarkos-dpc = { path = "../dpc", version = "1.0.0" }
snarkos-errors = { path = "../errors", version = "1.0.0" }
snarkos-models = { path = "../models", version = "1.0.0" }
snarkos-objects = { path= "../objects", version = "1.0.0" }
snarkos-posw = { path = "../posw", version = "1.0.0" }
snarkos-profiler = { path = "../profiler", version = "1.0.0" }
snarkos-storage = { path = "../storage", version = "1.0.0" }
snarkos-utilities = { path = "../utilities", version = "1.0.0" }

bincode = { version="1.3.1" }
chrono = { version = "0.4", features = ["serde"] }
hex = { version = "0.4.2" }
log = { version = "0.4.11" }
rand = { version = "0.7.3" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2.22", features = ["full"] }

[dev-dependencies]
snarkos-testing = { path = "../testing", version = "1.0.0" }

futures-await-test = { version = "0.3.0" }
rand_xorshift = { version = "0.2" }
