[package]
name = "snarkos-node-metrics"
version = "2.2.7"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A node for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[features]
metrics = [ "snarkvm/metrics" ]

[dependencies.metrics]
version = "0.22"

[dependencies.metrics-exporter-prometheus]
version = "0.13"

[dependencies.snarkvm]
workspace = true
features = [ "metrics" ]

[dependencies.tokio]
version = "1.28"
features = [ "rt" ]
