[package]
name = "snarkos-metrics"
version = "1.3.11"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Metrics for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[features]
std = [ ]
prometheus = [ "metrics-exporter-prometheus" ]

[dependencies.metrics]
version = "0.17"

[dependencies.metrics-exporter-prometheus]
version = "0.6"
optional = true

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.tokio]
version = "1"
features = [ "macros", "rt-multi-thread" ]

[dev-dependencies.snarkvm-derives]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "4c8b7e2"
# path = "../../snarkVM/derives"
