[package]
name = "snarkos-metrics"
version = "1.1.4"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Metrics for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
futures-util = { version = "0.3.5", default-features = false }
lazy_static = { version = "1.4" }
prometheus = { version = "0.11", features = ["process"] }
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3" }

[dev-dependencies]
snarkvm-derives = { version = "0.0.3" }

serial_test = { version = "0.5.0" }
